env:
  browser: true
  es2020: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - jest
rules: {
  "no-underscore-dangle": "off",
  "consistent-return": "off",
  "no-restricted-syntax": "off",
  "import/no-cycle": "off",
}
settings:
  import/resolver:
    webpack:
      config: 'webpack.lib.config.js'
