env:
  browser: true
  es2020: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  "jsx-a11y/label-has-associated-control": "off"
}
settings:
  import/resolver:
    webpack:
      config: 'webpack.demo.config.js'
